# H2 Database

spring.datasource.url=jdbc:h2:mem:elearn
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

event.publisher=local

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


# Eureka

eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.uuid}

# Mail

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}


# Actuator

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always