# H2 Database
spring.datasource.url=jdbc:h2:mem:elearn
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=false
eureka.instance.hostname=elearn-user-service.onrender.com

eureka.instance.non-secure-port-enabled=false

eureka.instance.secure-port-enabled=true

eureka.instance.status-page-url=https://elearn-user-service.onrender.com/actuator/info

eureka.instance.health-check-url=https://elearn-user-service.onrender.com/actuator/health

eureka.instance.home-page-url=https://elearn-user-service.onrender.com
# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
