# DEV MODE (NO DB)

# Disable DB completely
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

# Eureka (local)
#eureka.client.service-url.defaultZone=http://localhost:${EUREKA_PORT:8761}/eureka/

eureka.client.service-url.defaultZone=${EUREKA_URL}

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Security
spring.security.user.name=${ADMIN_USER:admin}
spring.security.user.password=${ADMIN_PASS:admin}

# Kafka (dummy)
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP:localhost:9092}

spring.mail.username=4188manil@gmail.com
spring.mail.password=12345678

eureka.client.initial-instance-info-replication-interval-seconds=5
eureka.client.registry-fetch-interval-seconds=5
